version: '3'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=Mikhail1
#      - POSTGRES_DB=yarzamata
#      - DATABASE_URL=postgresql://postgres:Mikhail1@db:5432/yarzamata?schema=public
#
#      - MONGODB_URI=mongodb+srv://MikhailSigma:AWcXfcDRX0m3F3b2@1.hxyck.mongodb.net/yarzamata?retryWrites=true&w=majority&appName=1
#    depends_on:
#      - db

#  db:
#    image: postgres:latest
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=Mikhail1
#      - POSTGRES_DB=yarzamata
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

#volumes:
#  postgres_data:
